import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import { GenericContainer } from 'testcontainers';
import type { StartedTestContainer } from 'testcontainers';
import { PostgreSqlContainer } from '@testcontainers/postgresql';
import type { StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { LoggerModule } from 'nestjs-pino';
import { Client as MinioClient } from 'minio';
import { PrismaService } from '../prisma/prisma.service';
import { FileRepository } from './file.repository';
import { FileService } from './file.service';
import { ObjectStoreService } from './object-store.service';
import { VaultTransitService } from './vault-transit.service';

jest.setTimeout(180_000);

// apps/api — where prisma.config.ts + prisma/ live.
const PKG_ROOT = join(__dirname, '..', '..');
const PRISMA_BIN = join(PKG_ROOT, 'node_modules', '.bin', 'prisma');

/**
 * storeGenerated is the export primitive (slice 18a): trusted server-rendered
 * bytes go through the SAME envelope as user uploads — only ciphertext lands in
 * MinIO — yet skip the upload MIME/size guards. Exercised against real stores.
 */
describe('FileService.storeGenerated (integration)', () => {
  let postgres: StartedPostgreSqlContainer;
  let vault: StartedTestContainer;
  let minio: StartedTestContainer;
  let pool: Pool;
  let prisma: PrismaService;
  let service: FileService;
  let rawMinio: MinioClient;

  beforeAll(async () => {
    [postgres, vault, minio] = await Promise.all([
      new PostgreSqlContainer('postgres:17-alpine').start(),
      new GenericContainer('hashicorp/vault:1.20')
        .withEnvironment({ VAULT_DEV_ROOT_TOKEN_ID: 'test-root-token' })
        .withExposedPorts(8200)
        .start(),
      new GenericContainer('minio/minio:latest')
        .withEnvironment({ MINIO_ROOT_USER: 'minio-test', MINIO_ROOT_PASSWORD: 'minio-secret' })
        .withCommand(['server', '/data'])
        .withExposedPorts(9000)
        .start(),
    ]);

    process.env.VAULT_ADDR = `http://${vault.getHost()}:${vault.getMappedPort(8200)}`;
    process.env.VAULT_TOKEN = 'test-root-token';
    process.env.MINIO_ENDPOINT = `http://${minio.getHost()}:${minio.getMappedPort(9000)}`;
    process.env.MINIO_ACCESS_KEY = 'minio-test';
    process.env.MINIO_SECRET_KEY = 'minio-secret';

    // Dev-mode Vault has no transit engine mounted yet.
    await fetch(`${process.env.VAULT_ADDR}/v1/sys/mounts/transit`, {
      method: 'POST',
      headers: { 'x-vault-token': 'test-root-token', 'content-type': 'application/json' },
      body: JSON.stringify({ type: 'transit' }),
    });

    pool = new Pool({ connectionString: postgres.getConnectionUri() });
    execFileSync(PRISMA_BIN, ['migrate', 'deploy'], {
      cwd: PKG_ROOT,
      env: { ...process.env, DATABASE_URL: postgres.getConnectionUri() },
      stdio: 'inherit',
    });
    process.env.DB_HOST = postgres.getHost();
    process.env.DB_PORT = String(postgres.getPort());
    process.env.DB_USER = postgres.getUsername();
    process.env.DB_PASSWORD = postgres.getPassword();
    process.env.DB_NAME = postgres.getDatabase();

    const moduleRef = await Test.createTestingModule({
      imports: [LoggerModule.forRoot({ pinoHttp: { level: 'silent' } })],
      providers: [
        FileService,
        FileRepository,
        ObjectStoreService,
        VaultTransitService,
        { provide: PrismaService, useValue: new PrismaService() },
      ],
    }).compile();
    await moduleRef.get(VaultTransitService).onModuleInit();
    await moduleRef.get(ObjectStoreService).onModuleInit();
    prisma = moduleRef.get(PrismaService);
    await prisma.$connect();
    service = moduleRef.get(FileService);

    rawMinio = new MinioClient({
      endPoint: minio.getHost(),
      port: minio.getMappedPort(9000),
      useSSL: false,
      accessKey: 'minio-test',
      secretKey: 'minio-secret',
    });
  });

  afterAll(async () => {
    await prisma?.$disconnect();
    await pool?.end();
    await Promise.allSettled([postgres?.stop(), vault?.stop(), minio?.stop()]);
    for (const key of [
      'VAULT_ADDR',
      'VAULT_TOKEN',
      'MINIO_ENDPOINT',
      'MINIO_ACCESS_KEY',
      'MINIO_SECRET_KEY',
    ]) {
      delete process.env[key];
    }
  });

  it('round-trips generated bytes: encrypt → store → download is byte-identical', async () => {
    // Arbitrary binary payload (a stand-in for a rendered docx/pdf) with a
    // recognisable plaintext marker to assert it never lands unencrypted.
    const content = Buffer.concat([
      Buffer.from('GENERATED-EXPORT-MARKER'),
      Buffer.from([0x00, 0xff, 0x10, 0x42, 0x7f]),
      Buffer.alloc(4096, 0xab),
    ]);

    const view = await service.storeGenerated(
      'auth0|alice',
      'conversation.pdf',
      'application/pdf',
      content,
    );
    expect(view).toMatchObject({
      name: 'conversation.pdf',
      mime: 'application/pdf',
      sizeBytes: content.length,
    });

    // What sits in MinIO is ciphertext — the marker must not be present.
    const { rows } = await pool.query<{ object_key: string }>(
      'SELECT object_key FROM files WHERE id = $1',
      [view.id],
    );
    const stored = await collect(await rawMinio.getObject('chatbot-files', rows[0].object_key));
    expect(stored.toString('latin1')).not.toContain('GENERATED-EXPORT-MARKER');
    expect(stored.equals(content)).toBe(false);

    // The owner gets the exact original bytes back through the decrypt path.
    const { meta, content: roundTripped } = await service.download('auth0|alice', view.id);
    expect(meta.id).toBe(view.id);
    expect(roundTripped.equals(content)).toBe(true);
  });

  it('bypasses the upload guards — stores oversized, non-allowlisted bytes', async () => {
    // Larger than MAX_RAW_BYTES (5MB) and a MIME the upload path rejects (415);
    // storeGenerated trusts server output and persists it regardless.
    const big = Buffer.alloc(6 * 1024 * 1024, 0x37);
    const view = await service.storeGenerated(
      'auth0|alice',
      'big.docx',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      big,
    );
    expect(view.sizeBytes).toBe(big.length);

    const { content } = await service.download('auth0|alice', view.id);
    expect(content.equals(big)).toBe(true);
  });

  it('scopes generated files to their owner — foreign download is 404', async () => {
    const view = await service.storeGenerated('auth0|alice', 'a.csv', 'text/csv', Buffer.from('x'));
    await expect(service.download('auth0|mallory', view.id)).rejects.toMatchObject({ status: 404 });
  });
});

async function collect(stream: NodeJS.ReadableStream): Promise<Buffer> {
  const chunks: Buffer[] = [];
  for await (const chunk of stream) {
    chunks.push(chunk as Buffer);
  }
  return Buffer.concat(chunks);
}
